# Generated by Django 2.1.3 on 2018-12-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='reg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='roll',
            field=models.IntegerField(default=0),
        ),
    ]
